version: "3.9"

services:
  student-statistics-process:
    build: .
    image: 5aleda4rf/student-statistics-process:latest
    volumes:
      - ./data:/app/data/batch
    ports:
      - "80:80"
    stdin_open: true
    tty: true

  registeration-process:
    build: .
    image: 5aleda4rf/registeration-process:latest
    volumes:
      - ./data:/app/data/batch
    ports:
      - "81:81"
    stdin_open: true
    tty: true



# Volumes Notes:-
# If you download this file in your pc, only put your local path instead of "./data" to mount it and run
# Like This:- Your Local Path:/app/data/batch
