name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
        
      - name: Build and run docker-image with the Dockerfile
        run: |
          docker build --tag students_statistics_system:v2.0 .
          
      - name: Build and run docker-compose
        run: |
          docker-compose build
          docker-compose up -d
          docker-compose down
